# Generated by Django 6.1 on 2026-08-23 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_id', models.CharField(max_length=20, unique=True)),
                ('vehicle', models.CharField(max_length=100)),
                ('incident_date', models.DateField()),
                ('description', models.TextField()),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=20)),
                ('status', models.CharField(choices=[('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('investigation', 'Investigation Required')], default='under_review', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('policyholder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('policyholder', 'Policyholder'), ('officer', 'Claim Officer'), ('admin', 'Administrator')], default='policyholder', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
