# Generated by Django 6.1 on 2026-08-27 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0005_policy_claim_policy'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsurancePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('plan_type', models.CharField(choices=[('Comprehensive', 'Comprehensive'), ('Third Party', 'Third Party'), ('Own Damage', 'Own Damage')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('insured_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('premium', models.DecimalField(decimal_places=2, max_digits=12)),
                ('duration_years', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='policy',
            name='insurance_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='policies', to='claims.insuranceplan'),
        ),
    ]
