# Generated by Django 6.1 on 2026-09-01 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0009_remove_userprofile_driver_license_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='days_to_report',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='claim',
            name='driver_age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='previous_claims',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
