# Generated by Django 5.2.4 on 2026-09-02 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0010_claim_days_to_report_claim_driver_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='ai_confidence',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
