# Generated by Django 5.2.4 on 2026-09-02 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0011_claim_ai_confidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='high_probability',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='low_probability',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='medium_probability',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
