# Generated by Django 6.1 on 2026-09-03 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0012_claim_high_probability_claim_low_probability_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='police_report',
        ),
        migrations.AddField(
            model_name='claim',
            name='damage_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='driver_authorised',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='incident_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='police_report_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='police_report_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='police_report_status',
            field=models.CharField(choices=[('reported', 'Reported'), ('not_reported', 'Not Reported'), ('not_required', 'Not Required')], default='not_required', max_length=20),
        ),
        migrations.AddField(
            model_name='claim',
            name='police_station',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='third_party_damage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='claim',
            name='third_party_injury',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='claim',
            name='third_party_involved',
            field=models.BooleanField(default=False),
        ),
    ]
