# Generated by Django 6.1 on 2026-09-03 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0013_remove_claim_police_report_claim_damage_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='damaged_parts',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='police_not_reported_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
