# Generated by Django 6.1 on 2026-09-06 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0014_claim_damaged_parts_claim_police_not_reported_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='driver_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='driving_license_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
