# Generated by Django 6.1 on 2026-09-06 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0015_claim_driver_name_claim_driving_license_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimdocument',
            name='ai_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claimdocument',
            name='extracted_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
